name: primitives_library_ffi
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path: ^1.8.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  test_utils:
    git:
      url: https://github.com/dart-lang/samples.git
      path: ffi/test_utils
      #ref: 091c89c984fbb13b7026c13fd2b8d02793cf4222

